// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3
// RUN: %driver -cc1 %isys %s %target -o %t%output-suffix && %filecheck

struct S;
extern S a[10];
S(*b)[10] = &a;
struct S {
  int x;
};

// The address calculation should be based on the size of the struct S
// declaration, not a dummy type like i8.

// CHECK-LABEL: define dso_local noundef i32 @_Z1fv
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr getelementptr inbounds ([10 x %struct.S], ptr @a, i64 0, i64 3), align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int f() { return a[3].x; }
